# Definindo o nome do Workflow
name: Workflow com docker

# Definindo quando o Workflow será disparado
on:
  push:
    branches: [ main, developer ]

# Definindo os jobs que o workflow executará
jobs:
  test_job:
    name: Executando o Job de Teste
    runs-on: ubuntu-latest
    steps:
    - name: Step 1
      uses: actions/checkout@v2

    - name: Docker Login   
      uses: docker/login-action@v3.3.0
      with:
        username: 'guilhermefausto'
        password: ${{ secrets.DOCKER_HUB_SECRET }}

    - name: Build and push Docker images
      uses: docker/build-push-action@v6.13.0
      with:
        context: .
        tags: 'latest'
        push: true
